#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: fring02/communities-forum:api-gateway
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          readOnlyRootFilesystem: true
          ports:
            - containerPort: 5006
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
#Service
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 5006
      targetPort: 5006
  type: LoadBalancer