#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: fring02/communities-forum:service-discovery
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          readOnlyRootFilesystem: true
          ports:
            - containerPort: 5001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
#Service
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  selector:
    app: service-discovery
  ports:
    - port: 5001
      targetPort: 5001
  type: LoadBalancer